import type { Metadata } from 'next';
import Link from 'next/link';

// These styles apply to every route in the application
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="text-white bg-portfolio-dark-background">
                <div className="w-[85%] mx-auto">
                    <div className="flex flex-items w-full gap-4 items-center justify-center">
                        <Link href="/"> Home</Link>
                        <Link href="/"> About Me</Link>
                        <Link href="/"> Services</Link>
                        <Link href="/"> Projects</Link>
                        <Link href="/"> Blogs</Link>
                    </div>
                    {children}
                </div>
            </body>
        </html>
    );
}
